version: 2.0

jobs:
  test:
    docker:
      - image: circleci/mongo
    steps:
      - checkout
      - run: sudo apt-get install maven
      - run: mvn test

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: sudo apt-get install maven
      - run: mvn -Dmaven.test.skip=true package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
